name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 10
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3

      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.10.0

      - name: Get swift version
        run: swift --version # Swift 5.9

      - name: Build DocC
        run: |
          swift package \
              --allow-writing-to-directory ./docs \
              generate-documentation --target TextEditorPlus \
              --disable-indexing \
              --transform-for-static-hosting \
              --hosting-base-path swiftui-texteditor \
              --output-path ./docs

      - name: Deploy Document
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs